version: '3.3'

services:
  post_db:
    image: mongo:${DB_IMAGE_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  post:
    image: ${USERNAME}/post:${POST_IMAGE_VERSION}
    depends_on:
      - post_db
    networks:
      - back_net
      - front_net

  comment:
    image: ${USERNAME}/comment:${COMMENT_IMAGE_VERSION}
    depends_on:
      - post_db
    networks:
      - back_net
      - front_net

  ui:
    image: ${USERNAME}/ui:${UI_IMAGE_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    depends_on:
      - post
      - comment
    networks:
      - front_net

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
