---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: reddit
    component: ui
spec:
  type: NodePort
  ports:
  - name: ui-port
    protocol: TCP
    port: 9292
    targetPort: 9292
  selector:
    app: reddit
    component: ui
